services:
  app:
    image: vehicle_world_api_app:1.0.0
    build:
      dockerfile: ./app.Dockerfile
    ports:
      - 50572:5000
    depends_on:
      - database
    volumes:
      - ./:/app
    restart: unless-stopped

  database:
    image: mongo:5.0.27
    env_file:
      - path: .env
        required: false
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/db_root_user
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MONGO_INITDB_DATABASE: ${DATABASE_NAME}
    volumes:
      - db_data:/data/db/
      - db_config:/data/configdb
    secrets:
      - db_root_user
      - db_root_password
    restart: unless-stopped

volumes:
  db_data:
  db_config:
  app:

secrets:
  db_root_user:
    file: ./docker_secrets/db_root_user.txt
  db_root_password:
    file: ./docker_secrets/db_root_password.txt
